### ISSUE TITLE
SSIS SharePoint List Adapter : String was not recognized as a valid Boolean

### ISSUE THREAD

**Issue by rsk2013** [japj/sqlsrvintegrationsrv#1]
We have a SharePoint list associated with Content Type.

When we tried to connect the List from SSIS console using List Adapter, we are getting the following error:

Error    1    Validation error. Import RCAL to Stage: Import RCAL to Stage: System.FormatException: **String was not recognized as a valid Boolean**.     at System.Boolean.Parse(String value)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.Adapter.ListsAdapter._Closure$__1._Closure$__2._Lambda$__4(XElement l, XElement m)     at System.Linq.Enumerable.<JoinIterator>d__37`4.MoveNext()     at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()     at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.Adapter.ListsAdapter.GetSharePointFields(String listName, String viewId)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.ListServiceUtility.GetFields(Uri sharepointUri, NetworkCredential credentials, String listName, String viewName)     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.GetAccessibleSharePointColumns(String sharepointUrl, String listName, String viewName)     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.ValidateSharePointColumns()     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.Validate()     at Microsoft.SqlServer.Dts.Pipeline.ManagedComponentHost.HostValidate(IDTSManagedComponentWrapper100 wrapper)    RigCorrectiveActionsLogImport.dtsx    0    0    
Error    1    Validation error. Import RCAL to Stage: Import RCAL to Stage: System.FormatException: String was not recognized as a valid Boolean.     at System.Boolean.Parse(String value)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.Adapter.ListsAdapter._Closure$__1._Closure$__2._Lambda$__4(XElement l, XElement m)     at System.Linq.Enumerable.<JoinIterator>d__37`4.MoveNext()     at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()     at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.Adapter.ListsAdapter.GetSharePointFields(String listName, String viewId)     at Microsoft.Samples.SqlServer.SSIS.SharePointUtility.ListServiceUtility.GetFields(Uri sharepointUri, NetworkCredential credentials, String listName, String viewName)     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.GetAccessibleSharePointColumns(String sharepointUrl, String listName, String viewName)     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.ValidateSharePointColumns()     at Microsoft.Samples.SqlServer.SSIS.SharePointListAdapters.SharePointListSource.Validate()     at Microsoft.SqlServer.Dts.Pipeline.ManagedComponentHost.HostValidate(IDTSManagedComponentWrapper100 wrapper)    RigCorrectiveActionsLogImport.dtsx    0    0    

Based on my investigation, some column in the Content Type is creating the issue.

Unfortunately, I am not able to locate the column in the Content Type which is causing the issue.

We have the same list with content type in our DEV/Testing environment. We do not have this issue there.

Any thoughts to identify the SharePoint list field causing this issue?

FYI: The list does not have any lookup fields. We are using Single Line of Text, Multiple Line of Text, Choice, Date and Time, Ppl Picker, Yes/No.

**Comment by japj** [comment]
@rsk2013 sorry it might not be clear, but this is/was merely a personal copy of the original codeplex repository from 2016. I am not developing or maintaining the actual code.
